QA-255: Do not build the mender-client from source unneeded
mendersoftware/integration-test-runner pull request #75
Opened 2021-02-12 13:06 UTC by oleorhagen

This takes advantage of the functionality in:

https://github.com/mendersoftware/mender-qa/pull/481

And sets BUILD_CLIENT == false, in the case a repository in the
prebuiltClientRepositories array is targeted.

Changelog: None

2021-02-12 13:06 UTC, oleorhagen commented
This goes along with: https://github.com/mendersoftware/mender-qa/pull/481

2021-02-15 08:24 UTC, kacf approved these changes

2021-02-15 09:35 UTC, lluiscampos requested changes
See my comment below. Does it make sense to you? Can you justify `mender-artifact` using a pre-build image?

2021-02-15 09:35 UTC, lluiscampos commented on main.go
> +var prebuiltClientRepositories = []string{
I think having a new list of repos is not wise: adding any repository we need to modify both `defaultWatchRepositoriesPipeline` and this one.

2021-02-15 09:35 UTC, lluiscampos commented on main.go
> +	"mender-artifact",
I guess this is the reason for the new list. I would argue that `mender-artifact` cannot use a pre-compiled yocto image -> mender-artifact is part of the image.

In my understanding, only repos not in `qemuBuildRepositories` are allowed to use a pre-compiled yocto image. (this links with my previous comment, as I don't think we need two lists)

2021-02-15 09:35 UTC, lluiscampos commented on menderqa_pipeline.go
> +	// Set BUILD_CLIENT == false, if target repo in prebuiltClientRepositories list
nitpick
```suggestion
	// Set BUILD_CLIENT = false, if target repo in prebuiltClientRepositories list
```

2021-02-15 12:00 UTC, lluiscampos approved these changes
Thanks! :100:

2021-02-15 12:01 UTC, lluiscampos commented
(Reminder: we cannot merge this PR before https://github.com/mendersoftware/mender-qa/pull/481)

2021-02-15 12:32 UTC, merged